{
  "hash": "af137967efc2ff4eec9a23f40f5700e7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Xuanyu Zhou\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-important}\n## Read this first, then delete this box\n\n**Where this file goes:** `assignments/assignment2.qmd` in your portfolio repo.\n\n**This is a portfolio piece.** It will be published on your website where employers\ncan see it. So:\n\n- **Delete every callout box like this one** before your final render. They're\n  instructions, not content.\n- Replace `YOUR NAME HERE` in the header above.\n- Write in complete sentences. Someone who isn't in this class should be able to\n  read it and follow what you did.\n\n**Graded 0 / 1 / 2.** A 2 means it runs, it's complete, and the writing shows you\nunderstood what the numbers meant — not that you did something fancy.\n\n**Due:** before next class. Rendered, committed, pushed, and visible on your live site.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n::: {.callout-tip}\n## Delete this box\n\nRewrite the paragraph below in your own words once you've picked your state and\nvariable. Two or three sentences saying what you're looking at and why.\n:::\n\n**In this analysis, I look at [YOUR VARIABLE] across counties in [YOUR STATE], and\nask which communities we measure most and least reliably.**\n\n---\n\n## Choosing what to measure\n\n::: {.callout-note}\n## Instructions — delete this box\n\nPick **a state** and **a variable**. Anything except Pennsylvania and median\nhousehold income, which we did in class.\n\nSome variables that work well:\n\n| Code | What it is |\n|------|-----------|\n| `B19013_001` | Median household income |\n| `B25064_001` | Median gross rent |\n| `B25077_001` | Median home value |\n| `B01002_001` | Median age |\n| `B08303_001` | Total commuters (travel time table) |\n| `B15003_022` | Number with a bachelor's degree |\n\nWant something else? Run this in your **console** (not in a chunk):\n\n```r\nvars <- load_variables(2023, \"acs5\")\nView(vars)\n```\n\nThen use the search box.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CA\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B01002_001     38.7   0.2\n2 06003 Alpine County, California    B01002_001     41.1   4.8\n3 06005 Amador County, California    B01002_001     49.9   0.6\n4 06007 Butte County, California     B01002_001     36.3   0.2\n5 06009 Calaveras County, California B01002_001     52     0.7\n6 06011 Colusa County, California    B01002_001     35.7   0.9\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Delete this box\n\nBelow, say how many counties are in your state and confirm your row count matches.\nOne sentence.\n:::\n\n**[How many rows did you get? Does that match the number of counties in your state?]**\n\n--- I get 58 counties and it does matches!\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n::: {.callout-note}\n## Delete this box\n\nFill in the two blanks. You want: how big is the margin of error, relative to the\nestimate, as a percentage?\n:::\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                         estimate   moe moe_pct\n   <chr>                           <dbl> <dbl>   <dbl>\n 1 Alpine County, California        41.1   4.8   11.7 \n 2 Sierra County, California        56     5      8.93\n 3 Mono County, California          40.3   1.8    4.47\n 4 Modoc County, California         49     2.1    4.29\n 5 Colusa County, California        35.7   0.9    2.52\n 6 Del Norte County, California     40.8   0.9    2.21\n 7 Mariposa County, California      51.6   1      1.94\n 8 Trinity County, California       54.8   0.9    1.64\n 9 Lassen County, California        37.8   0.6    1.59\n10 Plumas County, California        52.1   0.8    1.54\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Delete this box\n\nWrite a sentence or two naming the least reliable county and its `moe_pct`.\n:::\n\n**[Which county has the largest margin of error relative to its estimate? How large\nis it?]**\n\n---Alpine County, at about 11.68%\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 0.5  ~ \"High confidence\",\n    moe_pct < 1 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    16\n2 Low confidence     16\n3 Moderate           26\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Delete this box\n\nThose cutoffs (5% and 10%) are a bit of a judgment call, not a law of nature. If almost\nevery county lands in one category, adjust them so the split is informative for\n*your* variable — then say in your writing that you changed them and why. (I have a feeling for county-level, you may end up in high confidence everywhere - is smaller geographies where it really shows up. So feel free to change those numbers around a bit)\n:::\n\n**[How many counties fall into each category?]**\n\n---16 in High confidence, 16 in Low confidence, and 26 in moderate. \n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 06001 Alameda County, California     38.7    0.2 1651949    NA\n2 06003 Alpine County, California      41.1    4.8    1695   234\n3 06005 Amador County, California      49.9    0.6   41029    NA\n4 06007 Butte County, California       36.3    0.2  209470    NA\n5 06009 Calaveras County, California   52      0.7   45995    NA\n6 06011 Colusa County, California      35.7    0.9   21895    NA\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Delete this box\n\nNotice the column names: `myvarE`, `myvarM`, `popE`, `popM`. The `E` and `M`\nsuffixes are estimate and margin of error.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         56        700685.\n2 Moderate                 2          2213 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Delete this box\n\nTwo blanks. What are you grouping by? What are you averaging?\n:::grouping by reliability, and average the estimate population\n\n::: {.callout-tip}\n## Delete this box\n\nThis table is the heart of the assignment. Describe what it shows in two or three\nsentences.\n:::\n\n**[What is the average population of high-confidence counties versus low-confidence\ncounties? Is there a pattern?]**\n\n--- The average population of high-confidence counties is 700,685 versus 2,213 for the low-confidence counties. Fewer population will bring lower confidence. \n\n## What this means for policy\n\n::: {.callout-important}\n## Instructions — delete this box\n\n**Write 200–250 words.** \n\nAddress all three:\n\n1. **Which communities in your state do we know the least about?** Name specific\n   counties from your results.\n2. **Why?** Connect the pattern to how the ACS actually works — it's a sample, and\n   smaller places yield smaller samples.\n3. **What could go wrong?** Imagine a state agency allocating funding using your\n   variable, treating every county's number as equally certain. Who is likely to be\n   hurt, and how?\n\nUse your own numbers. \n:::\n\n**[Your 200–250 word reflection goes here.]**\n\n---\n\n## Optional challenges - For those craving more\n\n::: {.callout-note}\n## Delete this box\n\n**None of these are graded.** There are no extra points. A complete, well-written assignment earns a 2 either way.\n\nThey're here for anyone who finished the above and found it straightforward. Pick\none (or more) that interests you. \n\n1. **Propagate the margin of error.** If you compute a derived value — a percentage,\n   a ratio, a sum — its uncertainty depends on the uncertainty of its inputs, and\n   you can't just carry the original MOE along. The Census Bureau publishes formulas\n   for this, and `tidycensus` implements them: `moe_sum()`, `moe_prop()`,\n   `moe_ratio()`. Compute something derived, and get its margin of error right.\n\n2. **Parameterize the report.** Add `params:` to the YAML so the state is an input\n   rather than hard-coded, and the same file regenerates for any state. Render it\n   from the terminal with `quarto render assignment2.qmd -P state:NY`.\n\n3. **Write a function and iterate.** Wrap the data pull in a function, then use\n   `purrr::map_dfr()` to run it across several states at once. Does the\n   small-places-are-noisier pattern hold everywhere, or are some states different?\n\n4. **Change the geographic scale.** Run the same variable at `geography = \"tract\"`\n   inside one county. Compare the margins of error to what you saw at county level.\n   What does that imply about the resolution at which you can actually trust ACS\n   data?\n\nIf you try one, add a short section describing what you did and what you found.\n:::\n\n---\n\n## Before you submit\n\n::: {.callout-note}\n## Delete this box — checklist\n\n- [ ] Your name is in the YAML header\n- [ ] Every instruction callout is deleted\n- [ ] Every `[bracketed prompt]` is replaced with your own writing\n- [ ] No `___` blanks remain anywhere\n- [ ] The file is at `assignments/assignment2.qmd`\n- [ ] **Session → Restart R**, then render the whole project. It works.\n- [ ] Committed and pushed\n- [ ] You opened your live site and looked at the published page\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}