{
  "hash": "605b63bf393310d7efed4a53cbd50bbc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Xuanyu Zhou\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n**In this analysis, I look at median age across counties in California, and\nask which communities we measure most and least reliably.**\n\n---\n\n## Choosing what to measure\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CA\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B01002_001     38.7   0.2\n2 06003 Alpine County, California    B01002_001     41.1   4.8\n3 06005 Amador County, California    B01002_001     49.9   0.6\n4 06007 Butte County, California     B01002_001     36.3   0.2\n5 06009 Calaveras County, California B01002_001     52     0.7\n6 06011 Colusa County, California    B01002_001     35.7   0.9\n```\n\n\n:::\n:::\n\n\n\n\n**[How many rows did you get? Does that match the number of counties in your state?]**\n\nI get 58 counties and it does matches. \n\n--- \n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                         estimate   moe moe_pct\n   <chr>                           <dbl> <dbl>   <dbl>\n 1 Alpine County, California        41.1   4.8   11.7 \n 2 Sierra County, California        56     5      8.93\n 3 Mono County, California          40.3   1.8    4.47\n 4 Modoc County, California         49     2.1    4.29\n 5 Colusa County, California        35.7   0.9    2.52\n 6 Del Norte County, California     40.8   0.9    2.21\n 7 Mariposa County, California      51.6   1      1.94\n 8 Trinity County, California       54.8   0.9    1.64\n 9 Lassen County, California        37.8   0.6    1.59\n10 Plumas County, California        52.1   0.8    1.54\n```\n\n\n:::\n:::\n\n\n\n\n**[Which county has the largest margin of error relative to its estimate? How large\nis it?]**\n\nAlpine County, at about 11.68%\n\n---\n\n## Sorting counties into reliability categories\n\nI use relative MOE cutoffs of 0.5% and 1% because the default cutoffs place most counties in the same category for median age. These stricter cutoffs help distinguish relative precision across counties; they are categories for this analysis, not official reliability standards. I use the same cutoffs throughout the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 0.5  ~ \"High confidence\",\n    moe_pct < 1 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    16\n2 Low confidence     16\n3 Moderate           26\n```\n\n\n:::\n:::\n\n\n\n\n**[How many counties fall into each category?]**\n\n16 in High confidence, 16 in Low confidence, and 26 in moderate. \n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 06001 Alameda County, California     38.7    0.2 1651949    NA\n2 06003 Alpine County, California      41.1    4.8    1695   234\n3 06005 Amador County, California      49.9    0.6   41029    NA\n4 06007 Butte County, California       36.3    0.2  209470    NA\n5 06009 Calaveras County, California   52      0.7   45995    NA\n6 06011 Colusa County, California      35.7    0.9   21895    NA\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 0.5  ~ \"High confidence\",\n    moe_pct < 1 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         16       1711758.\n2 Low confidence          16         25185.\n3 Moderate                26        440450.\n```\n\n\n:::\n:::\n\n\n\n\n**[What is the average population of high-confidence counties versus low-confidence\ncounties? Is there a pattern?]**\n\nThe 16 high-confidence counties have an average population of 1,711,758.31, compared with 25,185.19 for the 16 low-confidence counties. The 26 moderate-confidence counties have an average population of 440,449.58. This pattern suggests that smaller counties tend to have less precise median age estimates in this analysis, although the comparison alone does not establish causation.\n\n---\n\n## What this means for policy\n\n\n**[Your 200–250 word reflection goes here.]**\n\nAmong California counties, Alpine and Sierra have the greatest relative uncertainty in their median age estimates. Alpine County has an estimated median age of 41.1 years and a margin of error (MoE) of 4.8 years (11.68% of the estimate). Sierra County has an estimated median age of 56 years and a MoE of 5 years (8.93%). Both are measured less precisely than other counties.\n\nUsing relative MOE cutoffs of 0.5% and 1%, the 16 high-confidence counties average roughly 1,711,758 residents, compared with 25,185 for the 16 low-confidence counties. The 26 moderate-confidence counties average 440,450. This pattern reflects how the ACS works: it surveys a sample of residents, and smaller counties yield fewer observations, so their estimates carry more uncertainty. \n\nSuppose a state agency used median age to prioritize funding for older-adult services. An underestimated median age might cause a county to miss support; an overestimate might divert funding from communities that need it. Alpine and Sierra would be especially exposed to such errors. Agencies should weigh MoE alongside point estimates — and recognize that median age alone does not capture the number of older residents who need services.\n\n\n---\n\n## Optional challenges - For those craving more\n\nUsing 2023 ACS five-year estimates, I compared the precision of median age estimates for Los Angeles County and its census tracts. The county's relative MOE was 0.26%, while the median relative MOE across 2,477 valid tracts was 10.12%. Another 21 tracts were excluded for missing estimates.\n\nWith reliability thresholds at 5% and 10%, 181 tracts (7.31%) fell into high confidence, 1,037 (41.87%) into moderate, and 1,259 (50.83%) into low confidence. \n\nA precise county estimate does not guarantee equally precise estimates at the tract level. Smaller areas yield fewer survey observations and more uncertainty. Agencies directing older-adult services to specific neighborhoods should check tract-level MOEs rather than relying on county precision alone.\n\n---\n\n## Before you submit\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}